version: '3.8'

services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - net1
  memgraph:
    image: memgraph/memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    networks:
      - net1
    volumes:
      - ./benchmark:/benchmark
  memgraph-lab:
    image: memgraph/lab
    ports:
      - "3000:3000"
    networks:
      - net1
    volumes:
      - ./benchmark:/benchmark
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7688:7687"
    environment:
      NEO4J_AUTH: "neo4j/neo4jneo4j"
      NEO4JLABS_PLUGINS: '["apoc", "n10s"]'
    networks:
      - net1
    volumes:
      - ./benchmark:/var/lib/neo4j/import/benchmark
      - ./neo4j-plugins:/plugins
      - ./neo4j-conf:/conf
  memdb-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./benchmark:/benchmark
    networks:
      - net1
  graphdb:
    image: ontotext/graphdb:10.7.1
    networks:
      - net1
    volumes:
      - ./benchmark:/benchmark
    ports:
      - "7200:7200"



networks:
  net1:
    driver: bridge
